# Base configs
# baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography By CreativeXMotion"
subtitle: "Creative Memories"
author: "2022 CreativeXMotion"
header:
 title: "CreativeXMotion"
#  subtitle: "by CreativeXMotion"
footer:
 name: "CreativeXMotion"
 bio: "Creative Memories"
#  github: ""
social_urls:
  # facebook: "https://www.facebook.com/"
  # twitter: "https://www.twitter.com/"
  instagram: "http://www.instagram.com/creativexmotion"
  tiktok: "https://www.tiktok.com/@creativexmotion"
  flickr: "https://flic.kr/ps/3Y83AY"