# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by CreativeXMotion"
subtitle: "See the world through my eyes!"
author: "CreativeXMotion"
header:
 title: "Photography"
 subtitle: "by CreativeXMotion"
footer:
 name: "Hey there, my name is Ram"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/"
  # twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/creativexmotion"
  tiktok: "https://www.tiktok.com/@creativexmotion"
  flickr: "https://flic.kr/ps/3Y83AY"