# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by CreativeXMotion"
subtitle: "See the world through my eyes!"
author: "CreativeXMotion"
header:
 title: "Photography"
 subtitle: "by CreativeXMotion"
footer:
 name: "CreativeXMotion"
 bio: "Photographers based in the GTA"
 github: ""
year: "2022"
social_urls:
  # facebook: "https://www.facebook.com/"
  # twitter: "https://www.twitter.com/"
  instagram: "http://www.instagram.com/creativexmotion"
  tiktok: "https://www.tiktok.com/@creativexmotion"
  flickr: "https://flic.kr/ps/3Y83AY"